version: '3.8'
services:
  mongo:
    container_name: mongoBd
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /home/kanu/Documentos/dokcer/mongo/data:/data/db
  mongo-express:
    container_name: mongoExpress
    image: mongo-express
    restart: always
    ports:
      - 2003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/