version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "2000:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_BD=postgres
    volumes:
      - "/home/kanu/Documentos/docker/postgres/data:/var/lib/postgresql/data"
  pgadmin:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "2001:80"
    depends_on:
      - postgres